// eSIMinder V2 — HTML shell: iOS-style login page + SPA shell.
import { STR } from '../i18n.js';
import { CLIENT_JS } from './client.js';

const LOGIN_CSS = 'body{font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text","PingFang SC","Microsoft YaHei",sans-serif;background:#f2f2f7;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;-webkit-tap-highlight-color:transparent}'
+ '[data-theme="dark"] body{background:#000}'
+ '.card{background:#fff;border-radius:20px;padding:32px 28px;width:330px;box-shadow:0 8px 30px rgba(0,0,0,.08);border:1px solid rgba(0,0,0,.06)}'
+ '.logo{font-size:44px;text-align:center;margin-bottom:8px}'
+ 'h1{font-size:24px;margin:0 0 4px;text-align:center;font-weight:700}'
+ '.sub{color:#8e8e93;font-size:14px;text-align:center;margin-bottom:24px}'
+ 'input{width:100%;box-sizing:border-box;padding:13px 14px;border:1px solid rgba(0,0,0,.1);border-radius:12px;font-size:16px;margin-bottom:12px;background:#f2f2f7;outline:none}'
+ 'input:focus{border-color:#007aff;background:#fff}'
+ 'button{width:100%;background:#007aff;color:#fff;border:none;border-radius:12px;padding:13px;font-size:16px;font-weight:600;cursor:pointer;transition:transform .1s}'
+ 'button:active{transform:scale(.98)}'
+ '#err{color:#ff3b30;font-size:13px;min-height:20px;margin-top:10px;text-align:center}'
+ '.lang{text-align:right;margin-bottom:12px}.lang a{color:#007aff;font-size:14px;cursor:pointer;text-decoration:none}';

export const LOGIN_PAGE = '<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8">'
+ '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">'
+ '<meta name="color-scheme" content="light dark">'
+ '<title>eSIMinder</title><style>' + LOGIN_CSS + '</style></head><body>'
+ '<div class="card"><div class="lang"><a onclick="toggleLang()" id="langLink">EN</a></div>'
+ '<div class="logo">📱</div><h1>eSIMinder</h1><div class="sub" id="loginSub"></div>'
+ '<div id="loginForm"><input id="pw" type="password" autocomplete="current-password">'
+ '<button onclick="doLogin()" id="loginBtn"></button></div>'
+ '<div id="pwForm" style="display:none"><div class="sub" id="mustChange" style="color:#ff9500"></div>'
+ '<input id="npw1" type="password" autocomplete="new-password">'
+ '<input id="npw2" type="password" autocomplete="new-password">'
+ '<button onclick="doChangePw()" id="changeBtn"></button></div>'
+ '<div id="err"></div></div>'
+ '<script>var STR=' + JSON.stringify(STR) + ';'
+ 'var LANG=localStorage.getItem("esiminder_lang")||"zh";'
+ 'function t(k){return (STR[LANG]&&STR[LANG][k])||STR.zh[k]||k;}'
+ 'function applyLang(){document.getElementById("loginSub").textContent=t("loginSub");'
+ 'document.getElementById("pw").placeholder=t("loginPwPh");'
+ 'document.getElementById("loginBtn").textContent=t("loginBtn");'
+ 'document.getElementById("npw1").placeholder=t("newPwPh");'
+ 'document.getElementById("npw2").placeholder=t("newPwPh");'
+ 'document.getElementById("changeBtn").textContent=t("changePwBtn");'
+ 'document.getElementById("mustChange").textContent=t("mustChangePw");'
+ 'document.getElementById("langLink").textContent=LANG==="zh"?"EN":"中文";'
+ 'document.documentElement.lang=LANG==="zh"?"zh-CN":"en";}'
+ 'function toggleLang(){LANG=LANG==="zh"?"en":"zh";localStorage.setItem("esiminder_lang",LANG);applyLang();}'
+ 'function err(s){document.getElementById("err").textContent=s;}'
+ 'async function doLogin(){err("");var pw=document.getElementById("pw").value;'
+ 'var r=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({adminToken:pw})});'
+ 'var d=await r.json().catch(function(){return{ok:false};});'
+ 'if(r.status===429){err(t("loginLocked"));return;}'
+ 'if(!d.ok){err(t("loginFail"));return;}'
+ 'if(d.mustChangePassword){document.getElementById("loginForm").style.display="none";document.getElementById("pwForm").style.display="block";applyLang();return;}'
+ 'location.href="/";}'
+ 'async function doChangePw(){err("");var a=document.getElementById("npw1").value,b=document.getElementById("npw2").value;'
+ 'if(a.length<6){err(t("pwShort"));return;}if(a!==b){err(t("loginFail"));return;}'
+ 'var r=await fetch("/api/admin-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({newPassword:a})});'
+ 'var d=await r.json().catch(function(){return{ok:false};});'
+ 'if(d.ok){location.href="/";}else{err(t("loginFail"));}}'
+ 'document.getElementById("pw").addEventListener("keydown",function(e){if(e.key==="Enter")doLogin();});'
+ 'applyLang();</script></body></html>';

export function appShell(settings) {
  return '<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8">'
  + '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">'
  + '<meta name="color-scheme" content="light dark">'
  + '<title>eSIMinder</title>'
  + '<script>window.__BOOT__=' + JSON.stringify({ theme: (settings && settings.theme) || 'system' }) + ';</script>'
  + '<script>window.__STR__=' + JSON.stringify(STR) + ';</script>'
  + '</head><body><div id="app"></div><div id="modal-root"></div><div id="toast-root"></div>'
  + '<script>' + CLIENT_JS + '</script></body></html>';
}
